Fixed bug when energy site name is null
zabuldon/teslajsonpy pull request #227
Opened 2021-10-16 21:16 UTC by giachello

closes https://github.com/alandtse/tesla/issues/62

2021-10-16 22:39 UTC, alandtse commented on teslajsonpy/controller.py
> +                self.__energysite_name[energysite_id] = energysite["site_name"]
```python
                self.__energysite_name[energysite_id] = energysite.get("site_name", "My Home")
```

2021-10-16 22:40 UTC, alandtse requested changes

2021-10-16 22:40 UTC, alandtse commented on teslajsonpy/controller.py
> +                self.__energysite_name[energysite_id] = energysite["site_name"]
Of course, please lint and make sure it works with a test.

2021-10-17 10:51 UTC, gwendalg commented
The change is not enough: "site_name" is also used in homeassistant/power.py, line 37:
`self._display_name: Text = data["site_name"]`
Using .get() with a default value is preferable, as the `_display_name` field is actively used in homeassistant.

2021-10-17 16:16 UTC, giachello commented
Using get and fixed power.py as well. implemented tests.

2021-10-17 18:04 UTC, merged