feat: add sch charge/depart properties and commands
zabuldon/teslajsonpy pull request #360
Opened 2022-11-03 03:12 UTC by InTheDaylight14

Work in progress. I'm not sure what parameters need to be updated when the command is successful. 

What is the goal for these blocks of code at the end of the command functions? Does it make sure that properties are updated without having to reach out and wait for the tesla API again?
```
if data and data["response"]["result"] is True:
  params = {"charge_limit_soc": int(value)}
  self._vehicle_data["charge_state"].update(params)
```

2022-11-03 18:54 UTC, InTheDaylight14 commented
End goal is to address this: https://github.com/alandtse/tesla/issues/164

2022-11-16 04:11 UTC, alandtse commented
> What is the goal for these blocks of code at the end of the command functions? Does it make sure that properties are updated without having to reach out and wait for the tesla API again?

Yes. But make sure the right values are populating the JSON.

2022-12-02 16:09 UTC, InTheDaylight14 commented
closes https://github.com/zabuldon/teslajsonpy/issues/370

2022-12-05 04:23 UTC, alandtse requested changes
Please address.

2022-12-05 15:31 UTC, InTheDaylight14 commented on teslajsonpy/car.py
> +    def off_peak_hours_end_time(self) -> int:
These I interpret as int because they are minutes after midnight. ```"off_peak_hours_end_time":360```

2022-12-05 15:37 UTC, InTheDaylight14 commented on teslajsonpy/car.py
> +    def off_peak_hours_end_time(self) -> int:
Does that work okay?

2022-12-05 19:24 UTC, alandtse commented on teslajsonpy/car.py
> +    def scheduled_departure_time(self) -> int:
I mean I'm not testing this. If you think it's an int or a timestamp, I'll go with whatever. Just let me know what you've confirmed.

2022-12-06 00:39 UTC, InTheDaylight14 commented on teslajsonpy/car.py
> +    def scheduled_departure_time(self) -> int:
I'm cool with int

2022-12-06 21:28 UTC, merged