feat: active route properties
zabuldon/teslajsonpy pull request #376
Opened 2022-12-05 16:59 UTC by InTheDaylight14

add properties for active route metrics
```
"active_route_destination": "Saved dest. name",
"active_route_energy_at_arrival": 40,
"active_route_latitude": 34.111111,
"active_route_longitude": -88.11111,
"active_route_miles_to_arrival": 19.849678,
"active_route_minutes_to_arrival": 34.133333,
"active_route_traffic_minutes_delay": 0.0,
```

Some are not available when parked. Will return None if key not available.

2022-12-05 19:25 UTC, alandtse commented on teslajsonpy/car.py
> +        return None
Technically, if it can return none, the typing should be `Optional[str]`.

2022-12-05 19:25 UTC, alandtse commented on teslajsonpy/car.py
> +    def _get_active_route_lat_long(self) -> float:
This typing is also wrong since you're returning a tuple.

2022-12-06 00:38 UTC, InTheDaylight14 commented on teslajsonpy/car.py
> +    def _get_lat_long(self) -> (float, float):
Thanks for catching that!

2022-12-09 17:36 UTC, alandtse requested changes
Just FYI, I'm waiting for you to address my comments and mark stuff resolved before I merge this in.

2022-12-09 20:04 UTC, InTheDaylight14 commented on teslajsonpy/car.py
> +    def _get_lat_long(self) -> (float, float):
I had missed the Optional par of that. 

```_get_lat_long``` was the original function for getting the current location. It has float as a typing comment. Not sure if that counts as fix release. I could break that out to a separate PR.

2022-12-10 06:46 UTC, merged